dist: xenial
language: cpp
compiler: clang
script:
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T mapreduce-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uhankhenshaw:$BINTRAY_API_KEY "https://api.bintray.com/content/hankhenshaw/MidRep/MapReduce/$TRAVIS_BUILD_NUMBER/mapreduce-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"